CREATE TABLE TIENDAS(
    NIF VARCHAR2(20),
    NOMBRE VARCHAR2(20),
    DIRECCION VARCHAR2(20),
    POBLACION VARCHAR2(20),
    PROVINCIA VARCHAR2(20),
    CODPOSTAL NUMBER(5)
);

ALTER TABLE TIENDAS MODIFY(

    NIF PRIMARY KEY NOT NULL,
    PROVINCIA CHECK (PROVINCIA = UPPER(PROVINCIA)),
    NOMBRE VARCHAR2(30) NOT NULL
    );
    
CREATE TABLE FABRICANTES(

COD_FABRICANTE NUMBER(3),
NOMBRE VARCHAR2(15),
PAIS VARCHAR2(15)
)

ALTER TABLE FABRICANTES MODIFY(
    COD_FABRICANTE PRIMARY KEY
    NOMBRE CHECK (NOMBRE = UPPER(NOMBRE)),
    PAIS CHECK (PAIS = UPPER(PAIS))
);