/*Creamos la tabla TIENDAS */
CREATE TABLE TIENDAS(
    NIF VARCHAR2(20),
    NOMBRE VARCHAR2(20),
    DIRECCION VARCHAR2(20),
    POBLACION VARCHAR2(20),
    PROVINCIA VARCHAR2(20),
    CODPOSTAL NUMBER(5)
);
/* Modificamos la tabla para establecer NIF como PK y no nulo
Establecemos que compruebe que provincia está en mayúsculas.
Establecemos nombre con una longitud variable de 30 caracteres y la restricción de no nulo
*/
ALTER TABLE TIENDAS MODIFY(

    NIF PRIMARY KEY NOT NULL,
    PROVINCIA CHECK (PROVINCIA = UPPER(PROVINCIA)),
    NOMBRE VARCHAR2(30) NOT NULL
    );
/* Se crea la tabla FABRICANTES */
CREATE TABLE FABRICANTES(

COD_FABRICANTE NUMBER(3),
    NOMBRE VARCHAR2(15),
    PAIS VARCHAR2(15)
);
/* Se modifica la tabla FABRICANTES para:
Establecer COD_FABRICANTE como clave primaria.
Comprobar que NOMBRE y PAIS está en mayúsculas.
*/
ALTER TABLE FABRICANTES MODIFY(
    COD_FABRICANTE PRIMARY KEY,
    NOMBRE CHECK (NOMBRE = UPPER(NOMBRE)),
    PAIS CHECK (PAIS = UPPER(PAIS))
);

CREATE TABLE ARTICULOS(
    
    ARTICULO VARCHAR2(20),
    COD_FABRICANTE NUMBER(3),
    PESO NUMBER(3),
    CATEGORIA VARCHAR2(10),
    PRECIO_VENTA NUMBER(6,2),
    PRECIO_COSTO NUMBER(6,2),
    EXISTENCIAS NUMBER(5),

    -- RESTRICCIONES --

    CONSTRAINT PK_ART PRIMARY KEY (ARTICULO, COD_FABRICANTE, PESO, CATEGORIA),
    CONSTRAINT FK_ART FOREIGN KEY (COD_FABRICANTE) REFERENCES FABRICANTES ON DELETE CASCADE,
    CONSTRAINT MAYOR CHECK (PRECIO_VENTA > 0 AND PRECIO_COSTO > 0 AND PESO > 0),
    CONSTRAINT CATEGORIA_CT CHECK (CATEGORIA IN ('Primera', 'Segunda', 'Tercera'))
);

CREATE TABLE VENTAS(
    NIF VARCHAR2(10),
    ARTICULO VARCHAR2(20),
    COD_FABRICANTE NUMBER(3),
    PESO NUMBER(3),
    CATEGORIA VARCHAR2(10),
    FECHA_VENTA DATE,
    UNIDADES_VENDIDAS NUMBER(4),
    
    --RESTRICCIONES--
    
    CONSTRAINT PK_VENTAS PRIMARY KEY(NIF, ARTICULO, COD_FABRICANTE, PESO, CATEGORIA, FECHA_VENTA),
    CONSTRAINT FK_VENTAS FOREIGN KEY(NIF) REFERENCES TIENDAS ON DELETE CASCADE,
    CONSTRAINT FK2_VENTAS FOREIGN KEY (ARTICULO, COD_FABRICANTE, PESO, CATEGORIA) REFERENCES ARTICULOS ON DELETE CASCADE,
    CONSTRAINT MAYOR_VENTAS CHECK( UNIDADES_VENDIDAS > 0)
);

CREATE TABLE PEDIDOS(

    NIF VARCHAR2(10),
    ARTICULO VARCHAR2(20),
    COD_FABRICANTE NUMBER(3),
    PESO NUMBER(3),
    CATEGORIA VARCHAR2(10),
    FECHA_PEDIDO DATE,
    UNIDADES_PEDIDAS NUMBER(4),
    EXISTENCIAS NUMBER(5),
    
    --RESTRICCIONES--
    
    CONSTRAINT PK_PEDIDOS PRIMARY KEY(NIF, ARTICULO,COD_FABRICANTE,PESO,CATEGORIA, FECHA_PEDIDO),
    CONSTRAINT FK_PEDIDOS FOREIGN KEY(NIF) REFERENCES TIENDAS ON DELETE CASCADE,
    CONSTRAINT FK2_PEDIDOS FOREIGN KEY(ARTICULO, COD_FABRICANTE, PESO, CATEGORIA) REFERENCES ARTICULOS ON DELETE CASCADE,
    CONSTRAINT UP_PEDIDOS CHECK(UNIDADES_PEDIDAS > 0),
    CONSTRAINT CATEGORIA_PEDIDOS CHECK(CATEGORIA IN('Primera','Segunda','Tercera'))
);

-- Añadir una restricción a la tabla TIENDAS para que el NOMBRE de la tienda sea de tipo título (InitCap).

ALTER TABLE TIENDAS MODIFY(
    CHECK(NOMBRE = InitCap(NOMBRE))
);

-- Visualizar las CONSTRAINTS definidas para las tablas anteriores.

    SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME IN('PEDIDOS','TIENDAS','VENTAS','FABRICANTES','ARTICULOS');

-- Modificar las columnas de las tablas PEDIDOS y VENTAS para que las UNIDADES_VENDIDAS y las UNIDADES_PEDIDAS puedan almacenar cantidades numéricas de 6 dígitos.

ALTER TABLE PEDIDOS MODIFY(
    UNIDADES_PEDIDAS NUMBER(6)
);

ALTER TABLE VENTAS MODIFY(
    UNIDADES_VENDIDAS NUMBER(6)
);

-- Impedir que se den de alta más tiendas en la provincia de ‘TOLEDO’.

ALTER TABLE TIENDAS MODIFY(
    CHECK(PROVINCIA <> 'TOLEDO')
);

-- Añadir a las tablas PEDIDOS y VENTAS una nueva columna para que almacenen el PVP del artículo.

ALTER TABLE PEDIDOS ADD(
    PVP NUMBER(6,2)
);

ALTER TABLE VENTAS ADD(
    PVP NUMBER(6,2)
);

-- Añadir a la tabla PROFESORES una columna llamada COD_ASIG con dos posiciones numéricas.

CREATE TABLE PROFESORES(

NIF VARCHAR2(10),
NOMBRE VARCHAR2(10),
APELLIDOS VARCHAR2(30),
MODULO VARCHAR2(10),
CURSO VARCHAR2(10)
);

ALTER TABLE PROFESORES ADD(
    COD_ASIG NUMBER(2)
);

-- Crear la tabla TASIG con las siguientes columnas: COD_ASIG numérico, 2 posiciones y NOM_ASIG cadena de 20 caracteres.

CREATE TABLE TASIG(
    COD_ASIG NUMBER(2),
    NOM_ASIG VARCHAR2(20)
);

-- Añadir la restricción de clave primaria a la columna COD_ASIG de la tabla TASIG.

ALTER TABLE TASIG MODIFY(
    COD_ASIG PRIMARY KEY
);

-- Añadir la restricción de clave ajena a la columna COD_ASIG de la tabla PROFESORES.

ALTER TABLE PROFESORES MODIFY(
    FOREIGN KEY (COD_ASIG) REFERENCES TASIG ON DELETE CASCADE
);

-- Cambiar de nombre la tabla PROFESORES y llamarla PROFES.

RENAME PROFESORES TO PROFES;

-- Borrar la tabla TASIG.

DROP TABLE TASIG CASCADE CONSTRAINT;

-- Devolver la tabla PROFESORES a su situación inicial (Renombrar).

RENAME PROFES TO PROFESORES;